package com.goloveschenko.weather.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.goloveschenko.weather.dao.OrmWeather;

import com.goloveschenko.weather.dao.OrmWeatherDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig ormWeatherDaoConfig;

    private final OrmWeatherDao ormWeatherDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        ormWeatherDaoConfig = daoConfigMap.get(OrmWeatherDao.class).clone();
        ormWeatherDaoConfig.initIdentityScope(type);

        ormWeatherDao = new OrmWeatherDao(ormWeatherDaoConfig, this);

        registerDao(OrmWeather.class, ormWeatherDao);
    }
    
    public void clear() {
        ormWeatherDaoConfig.clearIdentityScope();
    }

    public OrmWeatherDao getOrmWeatherDao() {
        return ormWeatherDao;
    }

}
