package com.goloveschenko.weather.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ORM_WEATHER".
*/
public class OrmWeatherDao extends AbstractDao<OrmWeather, Long> {

    public static final String TABLENAME = "ORM_WEATHER";

    /**
     * Properties of entity OrmWeather.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CityId = new Property(1, String.class, "cityId", false, "CITY_ID");
        public final static Property Location = new Property(2, String.class, "location", false, "LOCATION");
        public final static Property Date = new Property(3, String.class, "date", false, "DATE");
        public final static Property IconCode = new Property(4, int.class, "iconCode", false, "ICON_CODE");
        public final static Property Details = new Property(5, String.class, "details", false, "DETAILS");
        public final static Property Humidity = new Property(6, int.class, "humidity", false, "HUMIDITY");
        public final static Property Pressure = new Property(7, double.class, "pressure", false, "PRESSURE");
        public final static Property Temp = new Property(8, int.class, "temp", false, "TEMP");
        public final static Property IsDay = new Property(9, boolean.class, "isDay", false, "IS_DAY");
    }


    public OrmWeatherDao(DaoConfig config) {
        super(config);
    }
    
    public OrmWeatherDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ORM_WEATHER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CITY_ID\" TEXT," + // 1: cityId
                "\"LOCATION\" TEXT," + // 2: location
                "\"DATE\" TEXT," + // 3: date
                "\"ICON_CODE\" INTEGER NOT NULL ," + // 4: iconCode
                "\"DETAILS\" TEXT," + // 5: details
                "\"HUMIDITY\" INTEGER NOT NULL ," + // 6: humidity
                "\"PRESSURE\" REAL NOT NULL ," + // 7: pressure
                "\"TEMP\" INTEGER NOT NULL ," + // 8: temp
                "\"IS_DAY\" INTEGER NOT NULL );"); // 9: isDay
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ORM_WEATHER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, OrmWeather entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String cityId = entity.getCityId();
        if (cityId != null) {
            stmt.bindString(2, cityId);
        }
 
        String location = entity.getLocation();
        if (location != null) {
            stmt.bindString(3, location);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(4, date);
        }
        stmt.bindLong(5, entity.getIconCode());
 
        String details = entity.getDetails();
        if (details != null) {
            stmt.bindString(6, details);
        }
        stmt.bindLong(7, entity.getHumidity());
        stmt.bindDouble(8, entity.getPressure());
        stmt.bindLong(9, entity.getTemp());
        stmt.bindLong(10, entity.getIsDay() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, OrmWeather entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String cityId = entity.getCityId();
        if (cityId != null) {
            stmt.bindString(2, cityId);
        }
 
        String location = entity.getLocation();
        if (location != null) {
            stmt.bindString(3, location);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(4, date);
        }
        stmt.bindLong(5, entity.getIconCode());
 
        String details = entity.getDetails();
        if (details != null) {
            stmt.bindString(6, details);
        }
        stmt.bindLong(7, entity.getHumidity());
        stmt.bindDouble(8, entity.getPressure());
        stmt.bindLong(9, entity.getTemp());
        stmt.bindLong(10, entity.getIsDay() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public OrmWeather readEntity(Cursor cursor, int offset) {
        OrmWeather entity = new OrmWeather( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // cityId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // location
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // date
            cursor.getInt(offset + 4), // iconCode
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // details
            cursor.getInt(offset + 6), // humidity
            cursor.getDouble(offset + 7), // pressure
            cursor.getInt(offset + 8), // temp
            cursor.getShort(offset + 9) != 0 // isDay
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, OrmWeather entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCityId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLocation(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDate(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIconCode(cursor.getInt(offset + 4));
        entity.setDetails(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setHumidity(cursor.getInt(offset + 6));
        entity.setPressure(cursor.getDouble(offset + 7));
        entity.setTemp(cursor.getInt(offset + 8));
        entity.setIsDay(cursor.getShort(offset + 9) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(OrmWeather entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(OrmWeather entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(OrmWeather entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
